[package]
name = "lilyplayer-web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
shuttle-service = { version = "0.3.3", features = ["web-rocket"] }
rocket = "0.5.0-rc.2"
ureq = "2.4.0"
lazy_static = "1.4.0"